name: fiap_technical_challenge_adj

services:

  challenge_data_user:
    container_name: challenge_data_user
    image: postgres:16.0
    ports:
      - "5501:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: always
    environment:
      - POSTGRES_DB=challenge_user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data_user:/var/lib/postgresql/data
    networks:
      - general


volumes:
  data_user:
    name: data_user

networks:
  general:
    name: general
    driver: bridge

