name: fiap_technical_challenge_adj

volumes:
  database_user:
    name: database_user

networks:
  net_applications: # conexão com infra-local com acesso a internet - tipo bridge
    name: net_applications
    driver: bridge

services:

  kafka-cluster:
    image: landoop/fast-data-dev:latest
    container_name: kafka-cluster
    hostname: kafka-cluster
    ports:
      - "2181:2181"            # ZooKeeper
      - "3030:3030"            # Landoop UI
      - "8081:8081"            # Schema Registry
      - "8082:8082"            # REST Proxy
      - "8083:8083"            # Kafka Connect
      - "9092:9092"            # Kafka Broker
      - "9581-9585:9581-9585"  # JMX Ports
    environment:
      ADV_HOST: 127.0.0.1      # Define o endereço de host para 127.0.0.1 (localhost) - precisará ajustar isso para o IP do host ou o nome do serviço na rede Docker
      RUNTESTS: 0              # Desativa testes iniciais para iniciar mais rápido
      SAMPLEDATA: 0            # Desativa dados de exemplo
      FORWARDLOGS: 0           # Desativa forwarding de logs
      DEBUG: 0                 # Desabilita modo debug
      CONNECT_HEAP: 512m       # Aloca heap para o Kafka Connect
      DISABLE: azure-documentdb,blockchain,bloomberg,cassandra,coap,druid,elastic,elastic5,ftp,hazelcast,hbase,influxdb,jms,kudu,mongodb,mqtt,redis,rethink,voltdb,yahoo,hdfs,jdbc,elasticsearch,s3,twitter
    healthcheck:
      test: [ "CMD", "netstat", "-ltn" ] # Verifica se os serviços estão ouvindo nas portas
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - net_applications

  challenge_user:
    container_name: challenge_user
    image: juniorsmartins/challenge_user:v0.0.1
    build:
      context: ../challenge_user/
      dockerfile: Dockerfile
      args:
        APP_NAME: "challenge_user"
        APP_VERSION: "v0.0.1"
        APP_DESCRIPTION: "Serviço de Crud e Login de usuários."
    ports:
      - "9050:9050"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    environment:
      - DB_HOST=challenge_data_user
      - DB_PORT=5432
      - DB_NAME=challenge_user
    restart: on-failure
    networks:
      - net_applications
    depends_on:
      challenge_data_user:
        condition: service_started
      kafka-cluster:
        condition: service_healthy

  challenge_data_user:
    container_name: challenge_data_user
    image: postgres:16.0
    ports:
      - "5501:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: on-failure
    environment:
      - POSTGRES_DB=challenge_user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_user:/var/lib/postgresql/data
    networks:
      - net_applications

