spring:
  config:
    activate:
      on-profile: prod

  sql:
    init:
      mode: never
      data-locations: []

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

